### PR TITLE
update for bug in water density when salinity > 0

### LINKED ISSUE #23: issue w/ salinity in density calculation
Seems the ^2 is missing in the source code
image

### PR DESCRIPTION
**Pull request by jordansread**
Fixes #23

### CODE REVIEW

**Comment by lawinslow** [comment]
Want to add a version increment to this?

**Comment by lawinslow** [comment]
[Here](https://github.com/GLEON/Lake-Analyzer/blob/master/Source/Run_LA.m#L3) if not also in the Readme.

**Comment by jread-usgs** [comment]
yes, I will add both to the PR :+1:

**Comment by jread-usgs** [comment]
I think we are all set now

**Comment by lawinslow** [comment]
:+1:

**Pull request merged**
